- name: instalando o httpd no CentOS
  yum: name=httpd state=present
  when: ansible_distribution == 'CentOS'

- name: iniciando o httpd no CentOS
  service: name=httpd state=restarted
  when: ansible_distribution == 'CentOS'
