- name: parando nginx
  service:
    name: nginx
    state: stopped
  ignore_errors: True

- name: removendo nginx no centos
  yum: name=nginx state=absent
  when: ansible_distribution == 'CentOS'

- name: removendo nginx no ubuntu/debian
  apt: name=nginx state=absent
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'
