apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mysql-statefulset
spec:
  serviceName: my-mysql
  template:
    metadata:
      labels:
       name: mysql-pod
    spec:
      containers:
        - name: mysql-container
          image: mysql:5.5
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: "listavip"
            - name: MYSQL_USER
              value: "lista_usr"
            - name: MYSQL_PASSWORD
              value: "lista_pwd"
            - name: MYSQL_ROOT_PASSWORD
              value: "root_pwd"
          volumeMounts:
            - name: mysql-volume
              mountPath: /var/lib/mysql
      volumes:
       - name: mysql-volume
         persistentVolumeClaim:
           claimName: mysql-claim