apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mysql-statefulset
spec:
  serviceName: mysql-statefulset-service
  template:
    metadata:
      labels:
       name: mysql-pod
    spec:
      containers:
        - name: mysql-container
          image: mysql:5.5
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: "loja"
            - name: MYSQL_USER
              value: "loja_usr"
            - name: MYSQL_PASSWORD
              value: "loja_pwd"
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "1"
          volumeMounts:
            - name: mysql-volume
              mountPath: /var/lib/mysql
      volumes:
       - name: mysql-volume
         persistentVolumeClaim:
           claimName: mysql-claim