apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: springboot-deployment
spec:
  template:
    metadata:
      labels:
       name: springboot-pod
    spec:
      containers:
        - name: springboot-container
          image: afonsobarrenha/springboot:1.13.0-SNAPSHOT
          ports:
            - containerPort: 8080