apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-statefulset
spec:
  selector:
  serviceName: "db"
  template:
    metadata:
      labels:
        name: mysql
    spec:
      containers:
      - name: mysql-container
        image: mysql
        ports:
          - containerPort: 3306
        volumeMounts:
        - name: mysql-volume
          mountPath: /var/lib/mysql
        env:
          - name: MYSQL_DATABASE
            value: "loja"
          - name: MYSQL_USER
            value: "root"
          - name: MYSQL_ALLOW_EMPTY_PASSWORD
            value: "1"
      volumes:
        - name: mysql-volume
          persistentVolumeClaim:
            claimName: configuracao-mysql
  volumeClaimTemplates:
  - metadata:
      name: configuracao-mysql
    spec:
      accessModes: 
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi