---
# tasks file for apache
- name: Role de instalaçaõ do puppet
  hosts: all
  vars:
    - texto: 'texto'
  tasks: 
  - include: configura_repositorios.yml
    when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'CentOS'
  - include: instala_agentes.yml
    when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'CentOS'
