---

- name: raspberry-provisioning
  hosts: all
  tasks:

  - name: Install a list of packages
    become: yes
    apt:
      name: "{{ packages }}"
      update_cache: yes
    vars:
      packages:
      - figlet
      - htop

  - name: Configure figlet in /etc/profile
    become: yes
    lineinfile: 
      path: /etc/profile
      line: "figlet -f small $(whoami)@$(hostname) - $(hostname -I | awk '{print $1;}')"
      create: yes