---
- name: instalação do gitlab
  hosts: gitlab
  tasks:
    - name: instalando pre requisitos
      yum: name={{ item }} state=present
      with_items:
      - curl 
      - policycoreutils-python 
      - openssh-server

    - name: habilitando o ssh
      service: name=sshd state=started enabled=true

#    - name: habilitando o firewalld
#      shell: firewall-cmd --permanent --add-service=http

    - name: reiniciando o firewalld
      service: name=firewalld state=stopped

    - name: instalando postfix
      yum: name=postfix state=present

    - name: habilitando postfix
      service: name=postfix state=started enabled=true

    - name: habilitando repo do gitlab
      shell: curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.rpm.sh | sudo bash

    - name: instalando o gitlab
      yum: name=gitlab-ce state=present
