---
- name: Testando o ansible
  hosts: prod
  tasks:
  - name: instalando o pacote sl
    apt: name=sl state=present update_cache=yes

  - name: removendo o pacote cowsay
    apt: name=cowsay state=absent 

  - name: garantindo usr games na path
    lineinfile: 
      path: /etc/profile
      line: "export PATH=$PATH:/usr/games"
      create: yes

  - name: garantindo hosts
    lineinfile:
      path: /etc/hosts
      create: yes
      line: "{{item}}"
    with_items:
    - "192.168.200.155 ubuntu1.salas4linux.com.br ubuntu1"
    - "192.168.200.168 ubuntu2.salas4linux.com.br ubuntu2"
    - "192.168.200.169 dev1.salas4linux.com.br dev1"
    - "192.168.200.196 dev2.salas4linux.com.br dev2"

  - name: garantindo bashrc
    copy: 
      src: files/bashrc
      dest: /root/.bashrc

  - name: instalando nginx
    apt: 
      name: nginx
      state: present
    notify: reinicia nginx

  handlers:
  - name: reinicia nginx
    service:
      name: nginx
      state: restarted
