version: '3'
services: 

  jenkins-blueocean:
    image: jenkinsci/blueocean
    container_name: jenkins-blueocean
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks: 
      - jenkins-network

  sonarqube:
    image: sonarqube
    container_name: sonarqube
    ports:
      - "9000:9000"
    networks:
      - jenkins-network
      - sonarqube-network
    environment:
      - sonar.jdbc.url=jdbc:postgresql://postgres:5432/sonar
    volumes:
      - sonarqube-conf:/opt/sonarqube/conf
      - sonarqube-data:/opt/sonarqube/data
      - sonarqube-extensions:/opt/sonarqube/extensions
    depends_on:
      - postgres

#  sonar:
#    image: sonarqube
#    container_name: sonar
#    ports:
#      - 9000:9000
#      - 9092:9092
#    networks:
#      - jenkins-network
#      - sonar-network
#    environment:
#      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres:5432/sonar
#    volumes:
#      - ./volumes/sonar-data/sonarqube/conf:/opt/sonarqube/conf
#      - ./volumes/sonar-data/sonarqube/data:/opt/sonarqube/data
#      - ./volumes/sonar-data/sonarqube/extensions:/opt/sonarqube/extensions
#      - ./volumes/sonar-data/sonarqube/lib/bundled-plugins:/opt/sonarqube/lib/bundled-plugins
#    depends_on:
#      - postgres

  postgres:
    image: postgres
    container_name: postgres
    networks:
      - sonarqube-network
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql-data:/var/lib/postgresql/data

#  postgres:
#    image: postgres
#    container_name: postgres
#    networks:
#      - sonar-network
#    environment:
#      - POSTGRES_USER=sonar
#      - POSTGRES_PASSWORD=sonar
#    volumes:
#      - ./volumes/postgres-data/postgresql:/var/lib/postgresql
#      - ./volumes/postgres-data/postgresql/data:/var/lib/postgresql/data

  nexus:
    image: sonatype/nexus3
    container_name: nexus 
    ports:
      - 8081:8081
    networks:
      - jenkins-network
    volumes:
      - nexus-data:/nexus-data

#  dev:
#    image: php:7.2-apache
#    container_name: dev
#    networks:
#      - app-network
#    volumes:
#      - ./volumes/dev-data:/var/www/html

#  pre:
#    image: php:7.2-apache
#    container_name: pre
#    networks:
#      - app-network
#    volumes:
#      - ./volumes/pre-data:/var/www/html

#  pro:
#    image: php:7.2-apache
#    container_name: pro
#    networks:
#      - app-network
#    volumes:
#      - ./volumes/pro-data:/var/www/html

volumes:
  jenkins-data:
  sonarqube-conf:
  sonarqube-data:
  sonarqube-extensions:
  nexus-data:
  postgresql:
  postgresql-data:

networks: 
  jenkins-network:
    driver: bridge
  sonarqube-network:
    driver: bridge
#  app-network:
#    driver: bridge