---
- name: Ansible!
  hosts: prod
  tasks:
  - name: instalando o pacote sl
    apt: name=sl state=present update_cache=yes

  - name: instalando o pacote figlet
    apt: name=figlet state=present update_cache=yes

  - name: garantindo usr games na path
    lineinfile: 
      path: /etc/profile
      line: "export PATH=$PATH:/usr/games"
      create: yes

  - name: garantindo figlet no bashrc
    lineinfile: 
      path: /root/.bashrc
      line: "figlet $(whoami)@$(hostname)"
      create: yes
      become: yes

  - name: garantindo hosts
    lineinfile:
      path: /etc/hosts
      create: yes
      line: "{{item}}"
    with_items:
    - "192.168.0.9  ubuntu1"
    - "192.168.0.11 ubuntu2"
    - "192.168.0.12 dev1"
    - "192.168.0.14 dev2"

  - name: garantindo README
    copy: 
      src: files/README.md
      dest: /root/README.md

#  - name: instalando nginx
#    apt: 
#      name: nginx
#      state: present
#    notify: reinicia nginx

#  handlers:
#  - name: reinicia nginx
#    service:
#      name: nginx
#      state: restarted
