---
- name: Looking for previous rancher-server running
  changed_when: false
  command: docker ps -a
  register: docker_containers

- name: docker_containers.stdout
  debug:
    msg: "{{docker_containers.stdout}}"

- name: Running rancher_server container
  when: '"rancher/server" not in docker_containers.stdout'
  shell: docker run -d --restart=unless-stopped -p 8080:8080 rancher/server

- name: Waiting for Rancher Server to start
  when: '"rancher/server" not in docker_containers.stdout'
  action: command docker logs 'rancher/server'
  register: rancher_logs
  until: rancher_logs.stdout.find("Listening on") != -1
  retries: 30
  delay: 10

