---
- name: Instalando o Rundeck
  hosts: rundeck
  tasks: 
  - name: instalando o rundeck
    yum: name="{{item}}" state=present
    with_items:
    - java-1.8.0
    - http://repo.rundeck.org/latest.rpm
    - rundeck
